core:
  server_location:
  instance_type_master:
  instance_type_worker:
  ami_id:
vpc:
  vpc_cidr_block:
  vpc_name:
  ip_permissions_inbound_public:
subnet:
  public_subnet_cidr:
  public_subnet_tag:
  private_subnet_cidr:
  private_subnet_tag: 
secgroup:
  key_pair_name: 
  public_security_group_name:
  public_security_group_description:
  ip_permissions_outbound_public:
  ip_permissions_inbound_private:
  private_security_group_name: 
  private_security_group_description: 
  key_pair_name_private: 
